apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: es-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: es-operator-e2e
subjects:
- kind: ServiceAccount
  name: es-operator
  namespace: {{{NAMESPACE}}}
